language: android

sudo: false

jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=27
    - ANDROID_BUILD_TOOLS_VERSION=26.0.1
    - ANDROID_EMU_API_LEVEL=22
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=8

before_install:
  - chmod +x gradlew
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager).
  - sdkmanager tools
  # Install the system image.
  - sdkmanager "system-images;android-$ANDROID_EMU_API_LEVEL;default;$ANDROID_ABI"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$ANDROID_EMU_API_LEVEL;default;$ANDROID_ABI"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMU_API_LEVEL

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build connectedCheck connectedAndroidTest -PdisablePreDex --stacktrace

after_success:
  - ./gradlew coveralls

after_failure:
  - "cat $TRAVIS_BUILD_DIR/app/build/reports/checkstyle/main.xml"
  - "cat $TRAVIS_BUILD_DIR/app/build/reports/findbugs/debug.xml"
  - "cat $TRAVIS_BUILD_DIR/app/build/reports/pmd/main.xml"
  - "cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml"
  - "cat $TRAVIS_BUILD_DIR/domain/build/reports/checkstyle/main.xml"
  - "cat $TRAVIS_BUILD_DIR/domain/build/reports/findbugs/debug.xml"
  - "cat $TRAVIS_BUILD_DIR/domain/build/reports/pmd/main.xml"
  - "cat $TRAVIS_BUILD_DIR/domain/build/reports/lint-results.xml"
